/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as JoinRouteImport } from './routes/join'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as ApiEmailInkRouteImport } from './routes/api/email-ink'
import { Route as ApiEmailTestRouteImport } from './routes/api/email-test'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as CreatorForgotPasswordRouteImport } from './routes/creator.forgot-password'
import { Route as CreatorInvitePreviewRouteImport } from './routes/creator.invite-preview'
import { Route as CreatorLoginRouteImport } from './routes/creator.login'
import { Route as CreatorSetPasswordRouteImport } from './routes/creator.set-password'
import { Route as HandoffFrontDeskRouteImport } from './routes/handoff.front-desk'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as JournalArticleTemplateRouteImport } from './routes/journal.article-template'
import { Route as JournalComingSoonRouteImport } from './routes/journal.coming-soon'
import { Route as JournalSitemapDotxmlRouteImport } from './routes/journal.sitemap[.]xml'
import { Route as OwnerCreatorProgramRouteImport } from './routes/owner.creator-program'
import { Route as OwnerJournalRouteImport } from './routes/owner.journal'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as SoapsSlugRouteImport } from './routes/soaps.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailInkRoute = ApiEmailInkRouteImport.update({
  id: '/api/email-ink',
  path: '/api/email-ink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailTestRoute = ApiEmailTestRouteImport.update({
  id: '/api/email-test',
  path: '/api/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorForgotPasswordRoute = CreatorForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorInvitePreviewRoute = CreatorInvitePreviewRouteImport.update({
  id: '/invite-preview',
  path: '/invite-preview',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorLoginRoute = CreatorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSetPasswordRoute = CreatorSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => CreatorRoute,
} as any)
const HandoffFrontDeskRoute = HandoffFrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => HandoffRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const JournalArticleTemplateRoute = JournalArticleTemplateRouteImport.update({
  id: '/article-template',
  path: '/article-template',
  getParentRoute: () => JournalRoute,
} as any)
const JournalComingSoonRoute = JournalComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSitemapDotxmlRoute = JournalSitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => JournalRoute,
} as any)
const OwnerCreatorProgramRoute = OwnerCreatorProgramRouteImport.update({
  id: '/owner/creator-program',
  path: '/owner/creator-program',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerJournalRoute = OwnerJournalRouteImport.update({
  id: '/owner/journal',
  path: '/owner/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoapsSlugRoute = SoapsSlugRouteImport.update({
  id: '/soaps/$slug',
  path: '/soaps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRouteWithChildren
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRouteWithChildren
  '/join': typeof JoinRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/email-ink': typeof ApiEmailInkRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/api/version': typeof ApiVersionRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/creator/forgot-password': typeof CreatorForgotPasswordRoute
  '/creator/invite-preview': typeof CreatorInvitePreviewRoute
  '/creator/login': typeof CreatorLoginRoute
  '/creator/set-password': typeof CreatorSetPasswordRoute
  '/handoff/front-desk': typeof HandoffFrontDeskRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/article-template': typeof JournalArticleTemplateRoute
  '/journal/coming-soon': typeof JournalComingSoonRoute
  '/journal/sitemap.xml': typeof JournalSitemapDotxmlRoute
  '/owner/creator-program': typeof OwnerCreatorProgramRoute
  '/owner/journal': typeof OwnerJournalRoute
  '/r/$slug': typeof RSlugRoute
  '/soaps/$slug': typeof SoapsSlugRoute
  '/creator/': typeof CreatorIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRouteWithChildren
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/email-ink': typeof ApiEmailInkRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/api/version': typeof ApiVersionRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/creator/forgot-password': typeof CreatorForgotPasswordRoute
  '/creator/invite-preview': typeof CreatorInvitePreviewRoute
  '/creator/login': typeof CreatorLoginRoute
  '/creator/set-password': typeof CreatorSetPasswordRoute
  '/handoff/front-desk': typeof HandoffFrontDeskRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/article-template': typeof JournalArticleTemplateRoute
  '/journal/coming-soon': typeof JournalComingSoonRoute
  '/journal/sitemap.xml': typeof JournalSitemapDotxmlRoute
  '/owner/creator-program': typeof OwnerCreatorProgramRoute
  '/owner/journal': typeof OwnerJournalRoute
  '/r/$slug': typeof RSlugRoute
  '/soaps/$slug': typeof SoapsSlugRoute
  '/creator': typeof CreatorIndexRoute
  '/journal': typeof JournalIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRouteWithChildren
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRouteWithChildren
  '/join': typeof JoinRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/email-ink': typeof ApiEmailInkRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/api/version': typeof ApiVersionRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/creator/forgot-password': typeof CreatorForgotPasswordRoute
  '/creator/invite-preview': typeof CreatorInvitePreviewRoute
  '/creator/login': typeof CreatorLoginRoute
  '/creator/set-password': typeof CreatorSetPasswordRoute
  '/handoff/front-desk': typeof HandoffFrontDeskRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/article-template': typeof JournalArticleTemplateRoute
  '/journal/coming-soon': typeof JournalComingSoonRoute
  '/journal/sitemap.xml': typeof JournalSitemapDotxmlRoute
  '/owner/creator-program': typeof OwnerCreatorProgramRoute
  '/owner/journal': typeof OwnerJournalRoute
  '/r/$slug': typeof RSlugRoute
  '/soaps/$slug': typeof SoapsSlugRoute
  '/creator/': typeof CreatorIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/creator'
    | '/faq'
    | '/handoff'
    | '/join'
    | '/journal'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/sign-in'
    | '/terms'
    | '/unsubscribe'
    | '/admin/orders'
    | '/api/email-ink'
    | '/api/email-test'
    | '/api/version'
    | '/checkout/return'
    | '/creator/forgot-password'
    | '/creator/invite-preview'
    | '/creator/login'
    | '/creator/set-password'
    | '/handoff/front-desk'
    | '/journal/$slug'
    | '/journal/article-template'
    | '/journal/coming-soon'
    | '/journal/sitemap.xml'
    | '/owner/creator-program'
    | '/owner/journal'
    | '/r/$slug'
    | '/soaps/$slug'
    | '/creator/'
    | '/journal/'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/faq'
    | '/handoff'
    | '/join'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/sign-in'
    | '/terms'
    | '/unsubscribe'
    | '/admin/orders'
    | '/api/email-ink'
    | '/api/email-test'
    | '/api/version'
    | '/checkout/return'
    | '/creator/forgot-password'
    | '/creator/invite-preview'
    | '/creator/login'
    | '/creator/set-password'
    | '/handoff/front-desk'
    | '/journal/$slug'
    | '/journal/article-template'
    | '/journal/coming-soon'
    | '/journal/sitemap.xml'
    | '/owner/creator-program'
    | '/owner/journal'
    | '/r/$slug'
    | '/soaps/$slug'
    | '/creator'
    | '/journal'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/creator'
    | '/faq'
    | '/handoff'
    | '/join'
    | '/journal'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/sign-in'
    | '/terms'
    | '/unsubscribe'
    | '/admin/orders'
    | '/api/email-ink'
    | '/api/email-test'
    | '/api/version'
    | '/checkout/return'
    | '/creator/forgot-password'
    | '/creator/invite-preview'
    | '/creator/login'
    | '/creator/set-password'
    | '/handoff/front-desk'
    | '/journal/$slug'
    | '/journal/article-template'
    | '/journal/coming-soon'
    | '/journal/sitemap.xml'
    | '/owner/creator-program'
    | '/owner/journal'
    | '/r/$slug'
    | '/soaps/$slug'
    | '/creator/'
    | '/journal/'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  FaqRoute: typeof FaqRoute
  HandoffRoute: typeof HandoffRouteWithChildren
  JoinRoute: typeof JoinRoute
  JournalRoute: typeof JournalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  ApiEmailInkRoute: typeof ApiEmailInkRoute
  ApiEmailTestRoute: typeof ApiEmailTestRoute
  ApiVersionRoute: typeof ApiVersionRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  OwnerCreatorProgramRoute: typeof OwnerCreatorProgramRoute
  OwnerJournalRoute: typeof OwnerJournalRoute
  RSlugRoute: typeof RSlugRoute
  SoapsSlugRoute: typeof SoapsSlugRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-ink': {
      id: '/api/email-ink'
      path: '/api/email-ink'
      fullPath: '/api/email-ink'
      preLoaderRoute: typeof ApiEmailInkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-test': {
      id: '/api/email-test'
      path: '/api/email-test'
      fullPath: '/api/email-test'
      preLoaderRoute: typeof ApiEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/forgot-password': {
      id: '/creator/forgot-password'
      path: '/forgot-password'
      fullPath: '/creator/forgot-password'
      preLoaderRoute: typeof CreatorForgotPasswordRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/invite-preview': {
      id: '/creator/invite-preview'
      path: '/invite-preview'
      fullPath: '/creator/invite-preview'
      preLoaderRoute: typeof CreatorInvitePreviewRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/login': {
      id: '/creator/login'
      path: '/login'
      fullPath: '/creator/login'
      preLoaderRoute: typeof CreatorLoginRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/set-password': {
      id: '/creator/set-password'
      path: '/set-password'
      fullPath: '/creator/set-password'
      preLoaderRoute: typeof CreatorSetPasswordRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/handoff/front-desk': {
      id: '/handoff/front-desk'
      path: '/front-desk'
      fullPath: '/handoff/front-desk'
      preLoaderRoute: typeof HandoffFrontDeskRouteImport
      parentRoute: typeof HandoffRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/article-template': {
      id: '/journal/article-template'
      path: '/article-template'
      fullPath: '/journal/article-template'
      preLoaderRoute: typeof JournalArticleTemplateRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/coming-soon': {
      id: '/journal/coming-soon'
      path: '/coming-soon'
      fullPath: '/journal/coming-soon'
      preLoaderRoute: typeof JournalComingSoonRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/sitemap.xml': {
      id: '/journal/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/journal/sitemap.xml'
      preLoaderRoute: typeof JournalSitemapDotxmlRouteImport
      parentRoute: typeof JournalRoute
    }
    '/owner/creator-program': {
      id: '/owner/creator-program'
      path: '/owner/creator-program'
      fullPath: '/owner/creator-program'
      preLoaderRoute: typeof OwnerCreatorProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/journal': {
      id: '/owner/journal'
      path: '/owner/journal'
      fullPath: '/owner/journal'
      preLoaderRoute: typeof OwnerJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soaps/$slug': {
      id: '/soaps/$slug'
      path: '/soaps/$slug'
      fullPath: '/soaps/$slug'
      preLoaderRoute: typeof SoapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CreatorRouteChildren {
  CreatorForgotPasswordRoute: typeof CreatorForgotPasswordRoute
  CreatorInvitePreviewRoute: typeof CreatorInvitePreviewRoute
  CreatorLoginRoute: typeof CreatorLoginRoute
  CreatorSetPasswordRoute: typeof CreatorSetPasswordRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorForgotPasswordRoute: CreatorForgotPasswordRoute,
  CreatorInvitePreviewRoute: CreatorInvitePreviewRoute,
  CreatorLoginRoute: CreatorLoginRoute,
  CreatorSetPasswordRoute: CreatorSetPasswordRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface HandoffRouteChildren {
  HandoffFrontDeskRoute: typeof HandoffFrontDeskRoute
}

const HandoffRouteChildren: HandoffRouteChildren = {
  HandoffFrontDeskRoute: HandoffFrontDeskRoute,
}

const HandoffRouteWithChildren =
  HandoffRoute._addFileChildren(HandoffRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalArticleTemplateRoute: typeof JournalArticleTemplateRoute
  JournalComingSoonRoute: typeof JournalComingSoonRoute
  JournalSitemapDotxmlRoute: typeof JournalSitemapDotxmlRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalArticleTemplateRoute: JournalArticleTemplateRoute,
  JournalComingSoonRoute: JournalComingSoonRoute,
  JournalSitemapDotxmlRoute: JournalSitemapDotxmlRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  CreatorRoute: CreatorRouteWithChildren,
  FaqRoute: FaqRoute,
  HandoffRoute: HandoffRouteWithChildren,
  JoinRoute: JoinRoute,
  JournalRoute: JournalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  ApiEmailInkRoute: ApiEmailInkRoute,
  ApiEmailTestRoute: ApiEmailTestRoute,
  ApiVersionRoute: ApiVersionRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  OwnerCreatorProgramRoute: OwnerCreatorProgramRoute,
  OwnerJournalRoute: OwnerJournalRoute,
  RSlugRoute: RSlugRoute,
  SoapsSlugRoute: SoapsSlugRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
