/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as ApiEmailInkRouteImport } from './routes/api/email-ink'
import { Route as ApiEmailTestRouteImport } from './routes/api/email-test'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as SoapsSlugRouteImport } from './routes/soaps.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailInkRoute = ApiEmailInkRouteImport.update({
  id: '/api/email-ink',
  path: '/api/email-ink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailTestRoute = ApiEmailTestRouteImport.update({
  id: '/api/email-test',
  path: '/api/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SoapsSlugRoute = SoapsSlugRouteImport.update({
  id: '/soaps/$slug',
  path: '/soaps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/email-ink': typeof ApiEmailInkRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/soaps/$slug': typeof SoapsSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/email-ink': typeof ApiEmailInkRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/soaps/$slug': typeof SoapsSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/email-ink': typeof ApiEmailInkRoute
  '/api/email-test': typeof ApiEmailTestRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/soaps/$slug': typeof SoapsSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/admin/orders'
    | '/api/email-ink'
    | '/api/email-test'
    | '/checkout/return'
    | '/soaps/$slug'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/admin/orders'
    | '/api/email-ink'
    | '/api/email-test'
    | '/checkout/return'
    | '/soaps/$slug'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/terms'
    | '/admin/orders'
    | '/api/email-ink'
    | '/api/email-test'
    | '/checkout/return'
    | '/soaps/$slug'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  ApiEmailInkRoute: typeof ApiEmailInkRoute
  ApiEmailTestRoute: typeof ApiEmailTestRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  SoapsSlugRoute: typeof SoapsSlugRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-ink': {
      id: '/api/email-ink'
      path: '/api/email-ink'
      fullPath: '/api/email-ink'
      preLoaderRoute: typeof ApiEmailInkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-test': {
      id: '/api/email-test'
      path: '/api/email-test'
      fullPath: '/api/email-test'
      preLoaderRoute: typeof ApiEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soaps/$slug': {
      id: '/soaps/$slug'
      path: '/soaps/$slug'
      fullPath: '/soaps/$slug'
      preLoaderRoute: typeof SoapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  ApiEmailInkRoute: ApiEmailInkRoute,
  ApiEmailTestRoute: ApiEmailTestRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  SoapsSlugRoute: SoapsSlugRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
