ALTER TABLE public.orders
  ADD COLUMN order_number bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN stripe_event_id text,
  ADD COLUMN customer_name text,
  ADD COLUMN amount_subtotal integer NOT NULL DEFAULT 0,
  ADD COLUMN amount_shipping integer NOT NULL DEFAULT 0,
  ADD COLUMN amount_tax integer NOT NULL DEFAULT 0,
  ADD COLUMN confirmation_sent_at timestamptz;

CREATE UNIQUE INDEX orders_order_number_key ON public.orders (order_number);
CREATE UNIQUE INDEX orders_payment_intent_id_key
  ON public.orders (payment_intent_id)
  WHERE payment_intent_id IS NOT NULL;

CREATE TABLE public.stripe_webhook_events (
  event_id text PRIMARY KEY,
  event_type text NOT NULL,
  checkout_session_id text NOT NULL,
  outcome text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.order_confirmation_deliveries (
  checkout_session_id text PRIMARY KEY REFERENCES public.orders(checkout_session_id) ON DELETE CASCADE,
  order_id uuid NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent', 'failed')),
  attempts integer NOT NULL DEFAULT 0,
  claimed_at timestamptz,
  sent_at timestamptz,
  provider_message_id text,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_confirmation_deliveries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.orders FROM anon, authenticated;
REVOKE ALL ON public.stripe_webhook_events FROM anon, authenticated;
REVOKE ALL ON public.order_confirmation_deliveries FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.stripe_webhook_events TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.order_confirmation_deliveries TO service_role;

CREATE POLICY "Store service manages Stripe webhook events"
ON public.stripe_webhook_events
FOR ALL TO service_role
USING (true)
WITH CHECK (true);

CREATE POLICY "Store service manages order confirmation deliveries"
ON public.order_confirmation_deliveries
FOR ALL TO service_role
USING (true)
WITH CHECK (true);

CREATE TRIGGER set_stripe_webhook_events_updated_at
BEFORE UPDATE ON public.stripe_webhook_events
FOR EACH ROW EXECUTE FUNCTION public.set_orders_updated_at();

CREATE TRIGGER set_order_confirmation_deliveries_updated_at
BEFORE UPDATE ON public.order_confirmation_deliveries
FOR EACH ROW EXECUTE FUNCTION public.set_orders_updated_at();

CREATE OR REPLACE FUNCTION public.record_stripe_checkout_event(
  p_event_id text,
  p_event_type text,
  p_checkout_session_id text,
  p_outcome text
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.stripe_webhook_events (
    event_id, event_type, checkout_session_id, outcome
  ) VALUES (
    p_event_id, p_event_type, p_checkout_session_id, p_outcome
  )
  ON CONFLICT (event_id) DO UPDATE
  SET outcome = EXCLUDED.outcome,
      updated_at = now();
END;
$$;

CREATE OR REPLACE FUNCTION public.record_paid_checkout(
  p_event_id text,
  p_event_type text,
  p_checkout_session_id text,
  p_payment_intent_id text,
  p_customer_email text,
  p_customer_name text,
  p_currency text,
  p_amount_subtotal integer,
  p_amount_shipping integer,
  p_amount_tax integer,
  p_amount_total integer,
  p_shipping_details jsonb,
  p_items jsonb
)
RETURNS TABLE(order_id uuid, order_number bigint)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order public.orders%ROWTYPE;
BEGIN
  INSERT INTO public.stripe_webhook_events (
    event_id, event_type, checkout_session_id, outcome
  ) VALUES (
    p_event_id, p_event_type, p_checkout_session_id, 'paid_recorded'
  )
  ON CONFLICT (event_id) DO UPDATE
  SET outcome = 'paid_recorded',
      updated_at = now();

  INSERT INTO public.orders (
    checkout_session_id,
    payment_intent_id,
    stripe_event_id,
    customer_email,
    customer_name,
    amount_subtotal,
    amount_shipping,
    amount_tax,
    amount_total,
    currency,
    payment_status,
    shipping_details,
    items
  ) VALUES (
    p_checkout_session_id,
    p_payment_intent_id,
    p_event_id,
    p_customer_email,
    p_customer_name,
    p_amount_subtotal,
    p_amount_shipping,
    p_amount_tax,
    p_amount_total,
    p_currency,
    'paid',
    p_shipping_details,
    p_items
  )
  ON CONFLICT (checkout_session_id) DO UPDATE
  SET payment_intent_id = COALESCE(public.orders.payment_intent_id, EXCLUDED.payment_intent_id),
      stripe_event_id = EXCLUDED.stripe_event_id,
      customer_email = EXCLUDED.customer_email,
      customer_name = EXCLUDED.customer_name,
      amount_subtotal = EXCLUDED.amount_subtotal,
      amount_shipping = EXCLUDED.amount_shipping,
      amount_tax = EXCLUDED.amount_tax,
      amount_total = EXCLUDED.amount_total,
      currency = EXCLUDED.currency,
      payment_status = 'paid',
      shipping_details = EXCLUDED.shipping_details,
      items = EXCLUDED.items,
      updated_at = now()
  RETURNING * INTO v_order;

  INSERT INTO public.order_confirmation_deliveries (
    checkout_session_id, order_id
  ) VALUES (
    v_order.checkout_session_id, v_order.id
  )
  ON CONFLICT (checkout_session_id) DO NOTHING;

  RETURN QUERY SELECT v_order.id, v_order.order_number;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_order_confirmation(p_checkout_session_id text)
RETURNS TABLE(order_id uuid)
LANGUAGE sql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  UPDATE public.order_confirmation_deliveries
  SET status = 'sending',
      attempts = attempts + 1,
      claimed_at = now(),
      updated_at = now()
  WHERE checkout_session_id = p_checkout_session_id
    AND (
      status IN ('pending', 'failed')
      OR (status = 'sending' AND claimed_at < now() - interval '10 minutes')
    )
  RETURNING order_id;
$$;

REVOKE ALL ON FUNCTION public.record_stripe_checkout_event(text, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_paid_checkout(text, text, text, text, text, text, text, integer, integer, integer, integer, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.claim_order_confirmation(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_stripe_checkout_event(text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_paid_checkout(text, text, text, text, text, text, text, integer, integer, integer, integer, jsonb, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_order_confirmation(text) TO service_role;
